# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: associate.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='associate.proto',
  package='Associate',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0f\x61ssociate.proto\x12\tAssociate\"$\n\x04\x44\x61ta\x12\x0f\n\x07payload\x18\x01 \x01(\x0c\x12\x0b\n\x03\x63rc\x18\x02 \x01(\x07\"\xe4\x02\n\x08ServerRx\x12\x16\n\x0e\x61ssociation_id\x18\x01 \x01(\r\x12\x17\n\x0fsequence_num_bi\x18\x02 \x01(\r\x12\x35\n\tassoc_req\x18\x03 \x01(\x0b\x32 .Associate.ServerRx.AssociateReqH\x00\x12\x44\n\x11\x61ssoc_release_req\x18\x04 \x01(\x0b\x32\'.Associate.ServerRx.AssociateReleaseReqH\x00\x12\x1f\n\x04\x64\x61ta\x18\x05 \x01(\x0b\x32\x0f.Associate.DataH\x00\x12:\n\x0ekeep_alive_req\x18\x06 \x01(\x0b\x32 .Associate.ServerRx.KeepAliveReqH\x00\x1a\x1f\n\x0c\x41ssociateReq\x12\x0f\n\x07version\x18\x01 \x01(\t\x1a\x15\n\x13\x41ssociateReleaseReq\x1a\x0e\n\x0cKeepAliveReqB\x05\n\x03Msg\"\xe7\x03\n\x08ServerTx\x12\x16\n\x0e\x61ssociation_id\x18\x01 \x01(\r\x12\x18\n\x10sequence_num_uni\x18\x02 \x01(\r\x12\x17\n\x0fsequence_num_bi\x18\x03 \x01(\r\x12\x35\n\tassoc_rep\x18\x04 \x01(\x0b\x32 .Associate.ServerTx.AssociateRepH\x00\x12\x44\n\x11\x61ssoc_release_rep\x18\x05 \x01(\x0b\x32\'.Associate.ServerTx.AssociateReleaseRepH\x00\x12\x1f\n\x04\x64\x61ta\x18\x06 \x01(\x0b\x32\x0f.Associate.DataH\x00\x12:\n\x0ekeep_alive_rep\x18\x07 \x01(\x0b\x32 .Associate.ServerTx.KeepAliveRepH\x00\x1a\x87\x01\n\x0c\x41ssociateRep\x12@\n\x0bstatus_code\x18\x01 \x01(\x0e\x32+.Associate.ServerTx.AssociateRep.StatusCode\"5\n\nStatusCode\x12\t\n\x05UNDEF\x10\x00\x12\x0b\n\x07SUCCESS\x10\x01\x12\x0f\n\x0bVERSION_ERR\x10\x02\x1a\x15\n\x13\x41ssociateReleaseRep\x1a\x0e\n\x0cKeepAliveRepB\x05\n\x03Msgb\x06proto3'
)



_SERVERTX_ASSOCIATEREP_STATUSCODE = _descriptor.EnumDescriptor(
  name='StatusCode',
  full_name='Associate.ServerTx.AssociateRep.StatusCode',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNDEF', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SUCCESS', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='VERSION_ERR', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=816,
  serialized_end=869,
)
_sym_db.RegisterEnumDescriptor(_SERVERTX_ASSOCIATEREP_STATUSCODE)


_DATA = _descriptor.Descriptor(
  name='Data',
  full_name='Associate.Data',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='payload', full_name='Associate.Data.payload', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='crc', full_name='Associate.Data.crc', index=1,
      number=2, type=7, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=66,
)


_SERVERRX_ASSOCIATEREQ = _descriptor.Descriptor(
  name='AssociateReq',
  full_name='Associate.ServerRx.AssociateReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='Associate.ServerRx.AssociateReq.version', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=348,
  serialized_end=379,
)

_SERVERRX_ASSOCIATERELEASEREQ = _descriptor.Descriptor(
  name='AssociateReleaseReq',
  full_name='Associate.ServerRx.AssociateReleaseReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=381,
  serialized_end=402,
)

_SERVERRX_KEEPALIVEREQ = _descriptor.Descriptor(
  name='KeepAliveReq',
  full_name='Associate.ServerRx.KeepAliveReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=404,
  serialized_end=418,
)

_SERVERRX = _descriptor.Descriptor(
  name='ServerRx',
  full_name='Associate.ServerRx',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='association_id', full_name='Associate.ServerRx.association_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sequence_num_bi', full_name='Associate.ServerRx.sequence_num_bi', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='assoc_req', full_name='Associate.ServerRx.assoc_req', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='assoc_release_req', full_name='Associate.ServerRx.assoc_release_req', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data', full_name='Associate.ServerRx.data', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='keep_alive_req', full_name='Associate.ServerRx.keep_alive_req', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_SERVERRX_ASSOCIATEREQ, _SERVERRX_ASSOCIATERELEASEREQ, _SERVERRX_KEEPALIVEREQ, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='Msg', full_name='Associate.ServerRx.Msg',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=69,
  serialized_end=425,
)


_SERVERTX_ASSOCIATEREP = _descriptor.Descriptor(
  name='AssociateRep',
  full_name='Associate.ServerTx.AssociateRep',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status_code', full_name='Associate.ServerTx.AssociateRep.status_code', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _SERVERTX_ASSOCIATEREP_STATUSCODE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=734,
  serialized_end=869,
)

_SERVERTX_ASSOCIATERELEASEREP = _descriptor.Descriptor(
  name='AssociateReleaseRep',
  full_name='Associate.ServerTx.AssociateReleaseRep',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=871,
  serialized_end=892,
)

_SERVERTX_KEEPALIVEREP = _descriptor.Descriptor(
  name='KeepAliveRep',
  full_name='Associate.ServerTx.KeepAliveRep',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=894,
  serialized_end=908,
)

_SERVERTX = _descriptor.Descriptor(
  name='ServerTx',
  full_name='Associate.ServerTx',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='association_id', full_name='Associate.ServerTx.association_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sequence_num_uni', full_name='Associate.ServerTx.sequence_num_uni', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sequence_num_bi', full_name='Associate.ServerTx.sequence_num_bi', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='assoc_rep', full_name='Associate.ServerTx.assoc_rep', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='assoc_release_rep', full_name='Associate.ServerTx.assoc_release_rep', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data', full_name='Associate.ServerTx.data', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='keep_alive_rep', full_name='Associate.ServerTx.keep_alive_rep', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_SERVERTX_ASSOCIATEREP, _SERVERTX_ASSOCIATERELEASEREP, _SERVERTX_KEEPALIVEREP, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='Msg', full_name='Associate.ServerTx.Msg',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=428,
  serialized_end=915,
)

_SERVERRX_ASSOCIATEREQ.containing_type = _SERVERRX
_SERVERRX_ASSOCIATERELEASEREQ.containing_type = _SERVERRX
_SERVERRX_KEEPALIVEREQ.containing_type = _SERVERRX
_SERVERRX.fields_by_name['assoc_req'].message_type = _SERVERRX_ASSOCIATEREQ
_SERVERRX.fields_by_name['assoc_release_req'].message_type = _SERVERRX_ASSOCIATERELEASEREQ
_SERVERRX.fields_by_name['data'].message_type = _DATA
_SERVERRX.fields_by_name['keep_alive_req'].message_type = _SERVERRX_KEEPALIVEREQ
_SERVERRX.oneofs_by_name['Msg'].fields.append(
  _SERVERRX.fields_by_name['assoc_req'])
_SERVERRX.fields_by_name['assoc_req'].containing_oneof = _SERVERRX.oneofs_by_name['Msg']
_SERVERRX.oneofs_by_name['Msg'].fields.append(
  _SERVERRX.fields_by_name['assoc_release_req'])
_SERVERRX.fields_by_name['assoc_release_req'].containing_oneof = _SERVERRX.oneofs_by_name['Msg']
_SERVERRX.oneofs_by_name['Msg'].fields.append(
  _SERVERRX.fields_by_name['data'])
_SERVERRX.fields_by_name['data'].containing_oneof = _SERVERRX.oneofs_by_name['Msg']
_SERVERRX.oneofs_by_name['Msg'].fields.append(
  _SERVERRX.fields_by_name['keep_alive_req'])
_SERVERRX.fields_by_name['keep_alive_req'].containing_oneof = _SERVERRX.oneofs_by_name['Msg']
_SERVERTX_ASSOCIATEREP.fields_by_name['status_code'].enum_type = _SERVERTX_ASSOCIATEREP_STATUSCODE
_SERVERTX_ASSOCIATEREP.containing_type = _SERVERTX
_SERVERTX_ASSOCIATEREP_STATUSCODE.containing_type = _SERVERTX_ASSOCIATEREP
_SERVERTX_ASSOCIATERELEASEREP.containing_type = _SERVERTX
_SERVERTX_KEEPALIVEREP.containing_type = _SERVERTX
_SERVERTX.fields_by_name['assoc_rep'].message_type = _SERVERTX_ASSOCIATEREP
_SERVERTX.fields_by_name['assoc_release_rep'].message_type = _SERVERTX_ASSOCIATERELEASEREP
_SERVERTX.fields_by_name['data'].message_type = _DATA
_SERVERTX.fields_by_name['keep_alive_rep'].message_type = _SERVERTX_KEEPALIVEREP
_SERVERTX.oneofs_by_name['Msg'].fields.append(
  _SERVERTX.fields_by_name['assoc_rep'])
_SERVERTX.fields_by_name['assoc_rep'].containing_oneof = _SERVERTX.oneofs_by_name['Msg']
_SERVERTX.oneofs_by_name['Msg'].fields.append(
  _SERVERTX.fields_by_name['assoc_release_rep'])
_SERVERTX.fields_by_name['assoc_release_rep'].containing_oneof = _SERVERTX.oneofs_by_name['Msg']
_SERVERTX.oneofs_by_name['Msg'].fields.append(
  _SERVERTX.fields_by_name['data'])
_SERVERTX.fields_by_name['data'].containing_oneof = _SERVERTX.oneofs_by_name['Msg']
_SERVERTX.oneofs_by_name['Msg'].fields.append(
  _SERVERTX.fields_by_name['keep_alive_rep'])
_SERVERTX.fields_by_name['keep_alive_rep'].containing_oneof = _SERVERTX.oneofs_by_name['Msg']
DESCRIPTOR.message_types_by_name['Data'] = _DATA
DESCRIPTOR.message_types_by_name['ServerRx'] = _SERVERRX
DESCRIPTOR.message_types_by_name['ServerTx'] = _SERVERTX
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Data = _reflection.GeneratedProtocolMessageType('Data', (_message.Message,), {
  'DESCRIPTOR' : _DATA,
  '__module__' : 'associate_pb2'
  # @@protoc_insertion_point(class_scope:Associate.Data)
  })
_sym_db.RegisterMessage(Data)

ServerRx = _reflection.GeneratedProtocolMessageType('ServerRx', (_message.Message,), {

  'AssociateReq' : _reflection.GeneratedProtocolMessageType('AssociateReq', (_message.Message,), {
    'DESCRIPTOR' : _SERVERRX_ASSOCIATEREQ,
    '__module__' : 'associate_pb2'
    # @@protoc_insertion_point(class_scope:Associate.ServerRx.AssociateReq)
    })
  ,

  'AssociateReleaseReq' : _reflection.GeneratedProtocolMessageType('AssociateReleaseReq', (_message.Message,), {
    'DESCRIPTOR' : _SERVERRX_ASSOCIATERELEASEREQ,
    '__module__' : 'associate_pb2'
    # @@protoc_insertion_point(class_scope:Associate.ServerRx.AssociateReleaseReq)
    })
  ,

  'KeepAliveReq' : _reflection.GeneratedProtocolMessageType('KeepAliveReq', (_message.Message,), {
    'DESCRIPTOR' : _SERVERRX_KEEPALIVEREQ,
    '__module__' : 'associate_pb2'
    # @@protoc_insertion_point(class_scope:Associate.ServerRx.KeepAliveReq)
    })
  ,
  'DESCRIPTOR' : _SERVERRX,
  '__module__' : 'associate_pb2'
  # @@protoc_insertion_point(class_scope:Associate.ServerRx)
  })
_sym_db.RegisterMessage(ServerRx)
_sym_db.RegisterMessage(ServerRx.AssociateReq)
_sym_db.RegisterMessage(ServerRx.AssociateReleaseReq)
_sym_db.RegisterMessage(ServerRx.KeepAliveReq)

ServerTx = _reflection.GeneratedProtocolMessageType('ServerTx', (_message.Message,), {

  'AssociateRep' : _reflection.GeneratedProtocolMessageType('AssociateRep', (_message.Message,), {
    'DESCRIPTOR' : _SERVERTX_ASSOCIATEREP,
    '__module__' : 'associate_pb2'
    # @@protoc_insertion_point(class_scope:Associate.ServerTx.AssociateRep)
    })
  ,

  'AssociateReleaseRep' : _reflection.GeneratedProtocolMessageType('AssociateReleaseRep', (_message.Message,), {
    'DESCRIPTOR' : _SERVERTX_ASSOCIATERELEASEREP,
    '__module__' : 'associate_pb2'
    # @@protoc_insertion_point(class_scope:Associate.ServerTx.AssociateReleaseRep)
    })
  ,

  'KeepAliveRep' : _reflection.GeneratedProtocolMessageType('KeepAliveRep', (_message.Message,), {
    'DESCRIPTOR' : _SERVERTX_KEEPALIVEREP,
    '__module__' : 'associate_pb2'
    # @@protoc_insertion_point(class_scope:Associate.ServerTx.KeepAliveRep)
    })
  ,
  'DESCRIPTOR' : _SERVERTX,
  '__module__' : 'associate_pb2'
  # @@protoc_insertion_point(class_scope:Associate.ServerTx)
  })
_sym_db.RegisterMessage(ServerTx)
_sym_db.RegisterMessage(ServerTx.AssociateRep)
_sym_db.RegisterMessage(ServerTx.AssociateReleaseRep)
_sym_db.RegisterMessage(ServerTx.KeepAliveRep)


# @@protoc_insertion_point(module_scope)
