# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tblctlsuite.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import tblctl_pb2 as tblctl__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='tblctlsuite.proto',
  package='TblCtlSuite',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x11tblctlsuite.proto\x12\x0bTblCtlSuite\x1a\x0ctblctl.proto\"9\n\x08ServerRx\x12$\n\x03\x63tl\x18\x01 \x01(\x0b\x32\x15.TblCtlProto.ServerRxH\x00\x42\x07\n\x05Prtcl\"9\n\x08ServerTx\x12$\n\x03\x63tl\x18\x01 \x01(\x0b\x32\x15.TblCtlProto.ServerTxH\x00\x42\x07\n\x05Prtclb\x06proto3'
  ,
  dependencies=[tblctl__pb2.DESCRIPTOR,])




_SERVERRX = _descriptor.Descriptor(
  name='ServerRx',
  full_name='TblCtlSuite.ServerRx',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ctl', full_name='TblCtlSuite.ServerRx.ctl', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='Prtcl', full_name='TblCtlSuite.ServerRx.Prtcl',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=48,
  serialized_end=105,
)


_SERVERTX = _descriptor.Descriptor(
  name='ServerTx',
  full_name='TblCtlSuite.ServerTx',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ctl', full_name='TblCtlSuite.ServerTx.ctl', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='Prtcl', full_name='TblCtlSuite.ServerTx.Prtcl',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=107,
  serialized_end=164,
)

_SERVERRX.fields_by_name['ctl'].message_type = tblctl__pb2._SERVERRX
_SERVERRX.oneofs_by_name['Prtcl'].fields.append(
  _SERVERRX.fields_by_name['ctl'])
_SERVERRX.fields_by_name['ctl'].containing_oneof = _SERVERRX.oneofs_by_name['Prtcl']
_SERVERTX.fields_by_name['ctl'].message_type = tblctl__pb2._SERVERTX
_SERVERTX.oneofs_by_name['Prtcl'].fields.append(
  _SERVERTX.fields_by_name['ctl'])
_SERVERTX.fields_by_name['ctl'].containing_oneof = _SERVERTX.oneofs_by_name['Prtcl']
DESCRIPTOR.message_types_by_name['ServerRx'] = _SERVERRX
DESCRIPTOR.message_types_by_name['ServerTx'] = _SERVERTX
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ServerRx = _reflection.GeneratedProtocolMessageType('ServerRx', (_message.Message,), {
  'DESCRIPTOR' : _SERVERRX,
  '__module__' : 'tblctlsuite_pb2'
  # @@protoc_insertion_point(class_scope:TblCtlSuite.ServerRx)
  })
_sym_db.RegisterMessage(ServerRx)

ServerTx = _reflection.GeneratedProtocolMessageType('ServerTx', (_message.Message,), {
  'DESCRIPTOR' : _SERVERTX,
  '__module__' : 'tblctlsuite_pb2'
  # @@protoc_insertion_point(class_scope:TblCtlSuite.ServerTx)
  })
_sym_db.RegisterMessage(ServerTx)


# @@protoc_insertion_point(module_scope)
